name: CDK8s Synth from Subdirectory

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  synth:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK8s CLI
        run: npm install -g cdk8s-cli

      - name: Run CDK8s Synth in b/
        working-directory: ./b
        run: |
          cdk8s synth

      - name: Copy files to b/rushi directory
        working-directory: ./b
        run: |
          mkdir -p rushi
          cp dist/*.yaml rushi/

      - name: Copy files from b/rushi to helm-repo/k8s
        run: |
          cp b/rushi/*.yaml helm-repo/k8s/

      - name: Commit and push synthesized YAMLs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add b/rushi/*.yaml helm-repo/k8s/*.yaml
          git commit -m "chore: synth YAMLs to b/rushi/ and helm-repo/k8s/" || echo "No changes to commit"
          git push origin main
